Adds support for targeting an async method's internal MoveNext method
pardeike/Harmony pull request #514
Opened 2023-03-02 13:58 UTC by Banane9

As the title says. This is particularly interesting for targeting an `async` method with a transpiler, whether using Attributes or manually finding it with the added `AsyncMoveNext` method in AccessTools.

I'm not sure where the tests should go / how they should look, but I did test it on a game that I write mods for.  
Works perfectly, although trying to use `IAsyncStateMachine` as the type for the `__instance` parameter causes a `FormatException` for invalid IL on the call to the patch method (that took a while to figure out).

![Definition of Patches](https://user-images.githubusercontent.com/2124570/222447224-75d7c771-5e0d-4800-bd22-22b6773c4e3c.png)

![Resulting output in log showing all patches are successfully applied](https://user-images.githubusercontent.com/2124570/222447695-18ad222d-81a4-4ddf-8acf-a08beacc50a1.png)

2023-03-02 14:25 UTC, pardeike commented
What’s the difference to [MethodType.Enumerator](https://harmony.pardeike.net/api/HarmonyLib.MethodType.html) ?

2023-03-02 15:50 UTC, Banane9 commented
Well, with MethodType.Enumerator it fails to find the method to patch, as it looks for a newobj opcode - but the actual contents of async methods don't use that.

Looking at an iterator method, those are also decorated with an `IteratorStateMachineAttribute`, which contains a reference to the type. They both share the `StateMachineAttribute` as a parent, so I suppose it could be merged together into a StateMachine one too (though that wouldn't be backwards compatible, I guess).

2023-03-20 18:50 UTC, Banane9 commented
Anything that would have to be changed/added for this? 👀

2023-03-21 01:53 UTC, pardeike commented
I would still like to see if we can merge this with the existing api. You mentioned that this would break backwards compatibility, in what way would that be a problem?

2023-03-21 14:44 UTC, Banane9 commented
I just mentioned it as a consideration - I don't know how you handle that sort of thing for Harmony.

Funnily enough, the way I understand it, renaming the `MethodType.Enumerator` enum value to something like `MethodType.StateMachine` and handling both through that would keep it binary compatible (as enum values are embedded directly as their numeric values), but code using it would have to be changed.

2023-03-21 23:36 UTC, pardeike requested changes
Just that one tiny cleanup

2023-03-21 23:36 UTC, pardeike commented on Harmony/Public/Attributes.cs
> +		/// <summary>This targets the MoveNext method of the async state machine that actually has the method's implementation</summary>
If you shorten the comment a bit (same style as AccessTools.cs:504) I'll approve the PR

2023-03-22 00:21 UTC, merged